import { readFileSync } from 'node:fs';
import path from 'node:path';
import { NetsuiteRecordType, RecordType, getClassOverrides } from '../model';

/** The same parse the generator script performs, so the test fails when the enum drifts from the installed types. */
function readDeclaredRecordTypes(): Array<[string, string]> {
    const declarationFile = require.resolve('@hitc/netsuite-types/N/record.d.ts');
    const source = readFileSync(declarationFile, 'utf8');
    const enumBlock = source.match(/export enum Type \{([^}]*)\}/);
    if (!enumBlock) throw new Error(`No 'export enum Type' found in ${declarationFile}.`);
    return [...enumBlock[1].matchAll(/^\s*([A-Z][A-Z0-9_]*)\s*=\s*'([a-z0-9_]+)'/gm)].map((match) => [match[1], match[2]]);
}

describe('NetsuiteRecordType', () => {
    it('mirrors every member of the N/record Type enum in the installed @hitc/netsuite-types', () => {
        const declared = readDeclaredRecordTypes();
        expect(declared.length).toBeGreaterThan(200);
        expect(Object.entries(NetsuiteRecordType)).toEqual(declared);
    });

    it('names the generated source file as generated', () => {
        const source = readFileSync(path.join(__dirname, '..', 'model', 'netsuite-record-type.ts'), 'utf8');
        expect(source.startsWith('// Generated by scripts/generateNetsuiteRecordTypes.mjs')).toBe(true);
    });

    it('is accepted by @RecordType as the record type id', () => {
        @RecordType(NetsuiteRecordType.SALES_ORDER)
        class SalesOrder {
            id!: number;
        }
        expect(getClassOverrides(SalesOrder).recordType).toBe('salesorder');
    });
});
