import * as nodePath from 'path';
import { emitConfigFile } from '../emit/config-file-emitter';
import { emitContextFile } from '../emit/context-file-emitter';
import { LIBRARY_PACKAGE_NAME, buildGeneratedFileHeader, readGeneratorVersion } from '../emit/header';
import { SerializationError, serializeToTypeScriptLiteral } from '../emit/serialize';
import { emitTypeFile } from '../emit/type-file-emitter';

describe('serializeToTypeScriptLiteral()', () => {
    it('serializes primitives, arrays, nested objects, and quoted keys', () => {
        const literal = serializeToTypeScriptLiteral({
            recordType: 'salesorder',
            'odd-key': "it's",
            count: 3,
            flag: false,
            nothing: null,
            skipped: undefined,
            empty: {},
            list: [1, 'two', [true]],
            none: [],
            multi: 'line\nbreak\r',
        });

        expect(literal).toBe([
            '{',
            "    recordType: 'salesorder',",
            "    'odd-key': 'it\\'s',",
            '    count: 3,',
            '    flag: false,',
            '    nothing: null,',
            '    empty: {},',
            '    list: [',
            '        1,',
            "        'two',",
            '        [',
            '            true,',
            '        ],',
            '    ],',
            '    none: [],',
            "    multi: 'line\\nbreak\\r',",
            '}',
        ].join('\n'));
    });

    it('serializes non-finite numbers as constants', () => {
        expect(serializeToTypeScriptLiteral([Number.POSITIVE_INFINITY, Number.NEGATIVE_INFINITY, Number.NaN], { indent: '' })).toBe('[\nNumber.POSITIVE_INFINITY,\nNumber.NEGATIVE_INFINITY,\nNumber.NaN,\n]');
    });

    it('emits referenced functions by identifier and rejects unknown functions', () => {
        const transform = () => undefined;
        expect(serializeToTypeScriptLiteral({ transform }, { functionReferences: new Map([[transform, 'trimText']]) })).toBe('{\n    transform: trimText,\n}');
        expect(() => serializeToTypeScriptLiteral({ transform })).toThrow(SerializationError);
        expect(() => serializeToTypeScriptLiteral({ transform })).toThrow("Function at '$.transform' must be exported from the model file");
    });

    it('rejects class instances and unsupported primitives', () => {
        expect(() => serializeToTypeScriptLiteral({ when: new Date(0) })).toThrow("Value at '$.when' is a Date instance");
        expect(() => serializeToTypeScriptLiteral(Symbol('x'))).toThrow("Value of type symbol at '$' cannot be serialized");
        expect(serializeToTypeScriptLiteral(Object.create(null))).toBe('{}');
    });
});

describe('readGeneratorVersion() and buildGeneratedFileHeader()', () => {
    it('finds the library version by walking up from the tooling directory', () => {
        expect(readGeneratorVersion()).toMatch(/^\d+\.\d+\.\d+/);
    });

    it('skips unrelated or unreadable package.json files and falls back to unknown', () => {
        const files: Record<string, string> = {
            [nodePath.resolve('/root/a/b/package.json')]: '{ broken',
            [nodePath.resolve('/root/a/package.json')]: JSON.stringify({ name: 'other', version: '9.9.9' }),
        };
        expect(readGeneratorVersion(nodePath.resolve('/root/a/b'), (filePath) => files[filePath])).toBe('unknown');
        files[nodePath.resolve('/root/package.json')] = JSON.stringify({ name: LIBRARY_PACKAGE_NAME, version: '1.2.3' });
        expect(readGeneratorVersion(nodePath.resolve('/root/a/b'), (filePath) => files[filePath])).toBe('1.2.3');
    });

    it('renders a header without timestamps', () => {
        expect(buildGeneratedFileHeader('Something.', '1.0.0')).toBe([
            '// <auto-generated>',
            '//   Something.',
            `//   Generated by ${LIBRARY_PACKAGE_NAME} 1.0.0. Do not edit; rerun the build step instead.`,
            '// </auto-generated>',
            '',
        ].join('\n'));
    });
});

describe('emitConfigFile()', () => {
    it('emits the config literal with type and function imports, aliasing renamed exports', () => {
        const trim = () => undefined;
        const unused = () => undefined;
        const aliased = () => undefined;
        const output = emitConfigFile({
            modelName: 'Customer',
            config: { recordType: 'customer', query: { from: { name: 'customer', alias: 'cust' } }, fields: { name: { queryFieldId: 'companyname', tableAlias: 'cust', transform: trim }, other: { queryFieldId: 'x', tableAlias: 'cust', transform: aliased } } },
            libraryModule: '@acme/orm',
            typesImportPath: './Customer.types.gen',
            functionImports: [
                { fn: trim, identifier: 'trim', exportName: 'trim', importPath: '../shared' },
                { fn: unused, identifier: 'unused', exportName: 'unused', importPath: '../shared' },
                { fn: aliased, identifier: 'trim_2', exportName: 'trim', importPath: '../other' },
            ],
            version: '1.0.0',
        });

        expect(output).toContain("import type { QueryConfig } from '@acme/orm';");
        expect(output).toContain("import type { Customer } from './Customer.types.gen';");
        expect(output).toContain("import { trim as trim_2 } from '../other';");
        expect(output).toContain("import { trim } from '../shared';");
        expect(output).not.toContain('unused');
        expect(output).toContain('export const CustomerConfig: QueryConfig<Customer> = {');
        expect(output).toContain('transform: trim,');
        expect(output).toContain('transform: trim_2,');
        expect(output.endsWith('};\n')).toBe(true);
    });
});

describe('emitTypeFile()', () => {
    it('emits named nested interfaces, the root interface, and helper types', () => {
        const output = emitTypeFile({
            modelName: 'SalesOrder',
            libraryModule: '@acme/orm',
            version: '1.0.0',
            types: {
                root: { name: 'SalesOrder', properties: [
                    { name: 'id', typeText: 'number', optional: false, isArray: false, fieldType: 'float' },
                    { name: 'memo', typeText: 'string | null', optional: true, isArray: false, fieldType: 'string' },
                    { name: 'lines', typeText: 'SalesOrderLine[]', optional: false, isArray: true, nestedShapeName: 'SalesOrderLine' },
                    { name: 'address', typeText: '{ city: string; }', optional: false, isArray: false, nestedShapeName: 'SalesOrderAddress' },
                ] },
                nested: [
                    { name: 'SalesOrderLine', properties: [{ name: 'itemId', typeText: 'number', optional: false, isArray: false, fieldType: 'float' }] },
                    Object.assign({ name: 'SalesOrderAddress', properties: [] }, { anonymous: true }),
                ],
            },
        });

        expect(output).toBe([
            '// <auto-generated>',
            '//   Plain types for the SalesOrder model.',
            `//   Generated by ${LIBRARY_PACKAGE_NAME} 1.0.0. Do not edit; rerun the build step instead.`,
            '// </auto-generated>',
            '',
            "import type { RecordGraphPatch } from '@acme/orm';",
            '',
            'export interface SalesOrderLine {',
            '    itemId: number;',
            '}',
            '',
            'export interface SalesOrder {',
            '    id: number;',
            '    memo?: string | null;',
            '    lines: SalesOrderLine[];',
            '    address: { city: string; };',
            '}',
            '',
            'export type SalesOrderPatch = RecordGraphPatch<SalesOrder>;',
            'export type SalesOrderCreate = Partial<SalesOrder>;',
            '',
        ].join('\n'));
    });
});

describe('emitContextFile()', () => {
    it('emits the schema, context type, and factory sorted by set name', () => {
        const output = emitContextFile({
            contextName: 'App',
            libraryModule: '@acme/orm',
            version: '1.0.0',
            models: [
                { modelName: 'SalesOrder', setName: 'salesOrders', configImportPath: './SalesOrder.config.gen' },
                { modelName: 'Customer', setName: 'customers', configImportPath: './Customer.config.gen' },
            ],
        });

        expect(output).toContain("import { createNetSuiteContext } from '@acme/orm';");
        expect(output).toContain("import { CustomerConfig } from './Customer.config.gen';\nimport { SalesOrderConfig } from './SalesOrder.config.gen';");
        expect(output).toContain('export const AppSchema = {\n    customers: CustomerConfig,\n    salesOrders: SalesOrderConfig,\n};');
        expect(output).toContain('export type AppContext = NetSuiteContextInstance<typeof AppSchema>;');
        expect(output).toContain('export function createAppContext(options?: NetSuiteContextOptions): AppContext {\n    return createNetSuiteContext(AppSchema, options);\n}');
    });
});
