import * as nodePath from 'path';
import { emitContextFile } from '../emit/context-file-emitter';
import { LIBRARY_PACKAGE_NAME, buildGeneratedFileHeader, readGeneratorVersion } from '../emit/header';
import { emitModelFile } from '../emit/model-file-emitter';
import { SerializationError, serializeToTypeScriptLiteral } from '../emit/serialize';
import { emitTypesFile } from '../emit/types-file-emitter';

describe('serializeToTypeScriptLiteral()', () => {
    it('serializes primitives, arrays, nested objects, and quoted keys', () => {
        const literal = serializeToTypeScriptLiteral({
            recordType: 'salesorder',
            'odd-key': "it's",
            count: 3,
            flag: false,
            nothing: null,
            skipped: undefined,
            empty: {},
            list: [1, 'two', [true]],
            none: [],
            multi: 'line\nbreak\r',
        });

        expect(literal).toBe([
            '{',
            "    recordType: 'salesorder',",
            "    'odd-key': 'it\\'s',",
            '    count: 3,',
            '    flag: false,',
            '    nothing: null,',
            '    empty: {},',
            '    list: [',
            '        1,',
            "        'two',",
            '        [',
            '            true,',
            '        ],',
            '    ],',
            '    none: [],',
            "    multi: 'line\\nbreak\\r',",
            '}',
        ].join('\n'));
    });

    it('serializes non-finite numbers as constants', () => {
        expect(serializeToTypeScriptLiteral([Number.POSITIVE_INFINITY, Number.NEGATIVE_INFINITY, Number.NaN], { indent: '' })).toBe('[\nNumber.POSITIVE_INFINITY,\nNumber.NEGATIVE_INFINITY,\nNumber.NaN,\n]');
    });

    it('emits referenced functions by identifier and rejects unknown functions', () => {
        const transform = () => undefined;
        expect(serializeToTypeScriptLiteral({ transform }, { functionReferences: new Map([[transform, 'trimText']]) })).toBe('{\n    transform: trimText,\n}');
        expect(() => serializeToTypeScriptLiteral({ transform })).toThrow(SerializationError);
        expect(() => serializeToTypeScriptLiteral({ transform })).toThrow("Function at '$.transform' must be exported from the model file");
    });

    it('rejects class instances and unsupported primitives', () => {
        expect(() => serializeToTypeScriptLiteral({ when: new Date(0) })).toThrow("Value at '$.when' is a Date instance");
        expect(() => serializeToTypeScriptLiteral(Symbol('x'))).toThrow("Value of type symbol at '$' cannot be serialized");
        expect(serializeToTypeScriptLiteral(Object.create(null))).toBe('{}');
    });
});

describe('readGeneratorVersion() and buildGeneratedFileHeader()', () => {
    it('finds the library version by walking up from the tooling directory', () => {
        expect(readGeneratorVersion()).toMatch(/^\d+\.\d+\.\d+/);
    });

    it('skips unrelated or unreadable package.json files and falls back to unknown', () => {
        const files: Record<string, string> = {
            [nodePath.resolve('/root/a/b/package.json')]: '{ broken',
            [nodePath.resolve('/root/a/package.json')]: JSON.stringify({ name: 'other', version: '9.9.9' }),
        };
        expect(readGeneratorVersion(nodePath.resolve('/root/a/b'), (filePath) => files[filePath])).toBe('unknown');
        files[nodePath.resolve('/root/package.json')] = JSON.stringify({ name: LIBRARY_PACKAGE_NAME, version: '1.2.3' });
        expect(readGeneratorVersion(nodePath.resolve('/root/a/b'), (filePath) => files[filePath])).toBe('1.2.3');
    });

    it('renders a header without timestamps', () => {
        expect(buildGeneratedFileHeader('Something.', '1.0.0')).toBe([
            '// <auto-generated>',
            '//   Something.',
            `//   Generated by ${LIBRARY_PACKAGE_NAME} 1.0.0. Do not edit; rerun the build step instead.`,
            '// </auto-generated>',
            '',
        ].join('\n'));
    });
});

describe('emitModelFile()', () => {
    const trim = () => undefined;
    const unused = () => undefined;
    const aliased = () => undefined;
    const recordOptions = {
        className: 'SalesOrder',
        libraryModule: '@acme/orm',
        typesImportPath: './types.gen',
        config: { recordType: 'salesorder', fields: { poNumber: { queryFieldId: 'otherrefnum', transform: trim }, memo: { queryFieldId: 'memo', transform: aliased } } },
        functionImports: [
            { fn: trim, identifier: 'trim', exportName: 'trim', importPath: '../shared' },
            { fn: unused, identifier: 'unused', exportName: 'unused', importPath: '../shared' },
            { fn: aliased, identifier: 'trim_2', exportName: 'trim', importPath: '../other' },
        ],
        fields: { poNumber: 'poNumber', memo: 'memo', customer: { id: 'customer.id', companyName: 'customer.companyName' }, lines: { item: { type: 'lines.item.type' } } },
        version: '1.0.0',
    };

    it('emits the config and field paths of a record type, importing its interface from the types file and re-exporting the types', () => {
        const output = emitModelFile({ ...recordOptions, repository: false });

        expect(output).toBe([
            '// <auto-generated>',
            '//   Generated config, field paths for the SalesOrder model.',
            `//   Generated by ${LIBRARY_PACKAGE_NAME} 1.0.0. Do not edit; rerun the build step instead.`,
            '// </auto-generated>',
            '',
            "import type { QueryConfig } from '@acme/orm';",
            "import type { SalesOrder } from './types.gen';",
            "import { trim as trim_2 } from '../other';",
            "import { trim } from '../shared';",
            '',
            "export type { SalesOrder, SalesOrderCreate, SalesOrderPatch } from './types.gen';",
            '',
            'export const SalesOrderConfig: QueryConfig<SalesOrder> = {',
            "    recordType: 'salesorder',",
            '    fields: {',
            '        poNumber: {',
            "            queryFieldId: 'otherrefnum',",
            '            transform: trim,',
            '        },',
            '        memo: {',
            "            queryFieldId: 'memo',",
            '            transform: trim_2,',
            '        },',
            '    },',
            '};',
            '',
            '/** Field paths of SalesOrder, for where(), orderBy(), and select(): `SalesOrderFields.<property>` at any depth. */',
            'export const SalesOrderFields = {',
            "    poNumber: 'poNumber',",
            "    memo: 'memo',",
            '    customer: {',
            "        id: 'customer.id',",
            "        companyName: 'customer.companyName',",
            '    },',
            '    lines: {',
            '        item: {',
            "            type: 'lines.item.type',",
            '        },',
            '    },',
            '} as const;',
            '',
        ].join('\n'));
        expect(output).not.toContain('unused');
        expect(output).not.toContain('export interface');
    });

    it('points at a types file outside the output directory', () => {
        const output = emitModelFile({ ...recordOptions, typesImportPath: '../../../common/types/models.gen', repository: false });
        expect(output).toContain("import type { SalesOrder } from '../../../common/types/models.gen';");
        expect(output).toContain("export type { SalesOrder, SalesOrderCreate, SalesOrderPatch } from '../../../common/types/models.gen';");
    });

    it('adds the base repository and its runtime imports when asked', () => {
        const output = emitModelFile({ ...recordOptions, repository: true });

        expect(output).toContain('//   Generated config, field paths, base repository for the SalesOrder model.');
        expect(output).toContain("import { RecordSet } from '@acme/orm';\nimport type { QueryConfig, QueryConfigSource, RecordSetOptions } from '@acme/orm';\nimport type { SalesOrder } from './types.gen';");
        expect(output.endsWith([
            'export class SalesOrderRepositoryBase extends RecordSet<SalesOrder> {',
            '    constructor(source: QueryConfigSource<SalesOrder> = SalesOrderConfig, options?: RecordSetOptions) {',
            '        super(source, options);',
            '    }',
            '}',
            '',
        ].join('\n'))).toBe(true);
    });
});

describe('emitTypesFile()', () => {
    const members = [
        { name: 'poNumber', optional: false, typeText: 'string | null' },
        { name: 'memo', optional: true, typeText: 'string | null' },
        { name: 'customer', optional: true, typeText: "Pick<Customer, 'id' | 'companyName'>" },
        { name: 'lines', optional: false, typeText: 'TransactionLine[]' },
    ];

    it('declares every interface and the helper types of record types, sorted by class name, with no runtime import', () => {
        const output = emitTypesFile({
            version: '1.0.0',
            libraryModule: '@acme/orm',
            classes: [
                { className: 'SalesOrder', baseClassName: 'Transaction', members, helperTypes: true },
                { className: 'Address', members: [{ name: 'city', optional: false, typeText: 'string | null' }], helperTypes: false },
            ],
        });

        expect(output).toBe([
            '// <auto-generated>',
            '//   The interface of every model and the helper types of every record type. Type-only; safe to share with a client.',
            `//   Generated by ${LIBRARY_PACKAGE_NAME} 1.0.0. Do not edit; rerun the build step instead.`,
            '// </auto-generated>',
            '',
            "import type { EntityCreate, EntityPatch } from '@acme/orm';",
            '',
            'export interface Address {',
            '    city: string | null;',
            '}',
            '',
            'export interface SalesOrder extends Transaction {',
            '    poNumber: string | null;',
            '    memo?: string | null;',
            "    customer?: Pick<Customer, 'id' | 'companyName'>;",
            '    lines: TransactionLine[];',
            '}',
            '',
            '/** What `update()` takes for a SalesOrder: a deep partial; subrecords merge, sublists take { update, add, remove }. */',
            'export type SalesOrderPatch = EntityPatch<SalesOrder>;',
            '/** What `create()` takes for a SalesOrder: a deep partial with sublists as arrays of partial lines. */',
            'export type SalesOrderCreate = EntityCreate<SalesOrder>;',
            '',
        ].join('\n'));
        expect(output).not.toContain('Config');
    });

    it('leaves the library import out when no class is a record type', () => {
        const output = emitTypesFile({ libraryModule: '@acme/orm', classes: [{ className: 'Address', members: [], helperTypes: false }], version: '1.0.0' });
        expect(output).not.toContain('import ');
        expect(output).toContain('export interface Address {\n}\n');
    });
});

describe('emitContextFile()', () => {
    it('emits the schema, repositories, context type, and factory sorted by set name', () => {
        const output = emitContextFile({
            contextName: 'App',
            libraryModule: '@acme/orm',
            version: '1.0.0',
            repositories: true,
            models: [
                { modelName: 'SalesOrder', setName: 'salesOrders', importPath: './SalesOrder.gen' },
                { modelName: 'Customer', setName: 'customers', importPath: './Customer.gen' },
            ],
        });

        expect(output).toContain("import { createNetSuiteContext } from '@acme/orm';");
        expect(output).toContain("import { CustomerConfig, CustomerRepositoryBase } from './Customer.gen';\nimport { SalesOrderConfig, SalesOrderRepositoryBase } from './SalesOrder.gen';");
        expect(output).toContain('export const AppSchema = {\n    customers: CustomerConfig,\n    salesOrders: SalesOrderConfig,\n};');
        expect(output).toContain('export const AppRepositories = {\n    customers: CustomerRepositoryBase,\n    salesOrders: SalesOrderRepositoryBase,\n};');
        expect(output).toContain('export type AppRepositoryMap = RepositoryMap<typeof AppSchema>;');
        expect(output).toContain('export type AppContext<TRepositories extends AppRepositoryMap = {}> = NetSuiteContextInstance<typeof AppSchema, MergeRepositories<typeof AppRepositories, TRepositories>>;');
        expect(output).toContain('export function createAppContext<TRepositories extends AppRepositoryMap = {}>(options: ContextFactoryOptions<TRepositories> = {}): AppContext<TRepositories> {\n    return createNetSuiteContext(AppSchema, { ...options, repositories: { ...AppRepositories, ...options.repositories } }) as unknown as AppContext<TRepositories>;\n}');
        expect(output).toContain("export type DbContext = Pick<AppContext, keyof typeof AppSchema> & {\n    withTracking<TRepositories extends AppRepositoryMap = {}>(options?: Omit<ContextFactoryOptions<TRepositories>, 'tracking'>): AppContext<TRepositories>;\n};");
        expect(output).toContain("function withTracking<TRepositories extends AppRepositoryMap = {}>(options: Omit<ContextFactoryOptions<TRepositories>, 'tracking'> = {}): AppContext<TRepositories> {\n    return createAppContext({ ...options, tracking: true });\n}");
        expect(output).toContain('export const dbContext: DbContext = {\n    get customers() { return getReadOnlyAppContext().customers; },\n    get salesOrders() { return getReadOnlyAppContext().salesOrders; },\n    withTracking,\n};');
        expect(output).not.toContain('UnitOfWork');
    });

    it('emits the plain schema, context type, and factory without repositories', () => {
        const output = emitContextFile({
            contextName: 'App',
            libraryModule: '@acme/orm',
            repositories: false,
            models: [{ modelName: 'Customer', setName: 'customers', importPath: './Customer.gen' }],
        });

        expect(output).toContain("import type { NetSuiteContextInstance, NetSuiteContextOptions } from '@acme/orm';");
        expect(output).toContain("import { CustomerConfig } from './Customer.gen';");
        expect(output).not.toContain('RepositoryBase');
        expect(output).toContain('export type AppContext = NetSuiteContextInstance<typeof AppSchema>;');
        expect(output).toContain('export function createAppContext(options?: NetSuiteContextOptions): AppContext {\n    return createNetSuiteContext(AppSchema, options);\n}');
        expect(output).toContain("export type DbContext = Pick<AppContext, keyof typeof AppSchema> & {\n    withTracking(options?: Omit<NetSuiteContextOptions, 'tracking'>): AppContext;\n};");
        expect(output).toContain('let readOnlyAppContext: AppContext | undefined;\n\nfunction getReadOnlyAppContext(): AppContext {\n    if (!readOnlyAppContext) readOnlyAppContext = createAppContext({ tracking: false });\n    return readOnlyAppContext;\n}');
        expect(output).toContain('export const dbContext: DbContext = {\n    get customers() { return getReadOnlyAppContext().customers; },\n    withTracking,\n};');
        expect(output).not.toContain('UnitOfWork');
    });
});
