import * as nodeFileSystem from 'fs';
import * as nodePath from 'path';

export const LIBRARY_PACKAGE_NAME = '@amerilux/netsuite-repository';

/** Finds the library's own package.json version by walking up from this file. Falls back to 'unknown'. */
export function readGeneratorVersion(startDirectory: string = __dirname, readFile: (filePath: string) => string | undefined = readFileIfExists): string {
    let current = nodePath.resolve(startDirectory);
    for (let depth = 0; depth < 8; depth++) {
        const content = readFile(nodePath.join(current, 'package.json'));
        if (content !== undefined) {
            try {
                const parsed = JSON.parse(content) as { name?: string; version?: string };
                if (parsed.name === LIBRARY_PACKAGE_NAME && typeof parsed.version === 'string') {
                    return parsed.version;
                }
            } catch {
                // Not a readable package.json; keep walking up.
            }
        }
        const parent = nodePath.dirname(current);
        if (parent === current) {
            break;
        }
        current = parent;
    }
    return 'unknown';
}

function readFileIfExists(filePath: string): string | undefined {
    return nodeFileSystem.existsSync(filePath) ? nodeFileSystem.readFileSync(filePath, 'utf8') : undefined;
}

export function buildGeneratedFileHeader(description: string, version: string = readGeneratorVersion()): string {
    return [
        '// <auto-generated>',
        `//   ${description}`,
        `//   Generated by ${LIBRARY_PACKAGE_NAME} ${version}. Do not edit; rerun the build step instead.`,
        '// </auto-generated>',
        '',
    ].join('\n');
}
