/**
 * Writes src/model/netsuite-record-type.ts: the `NetsuiteRecordType` enum, a runtime copy of the
 * `Type` enum that @hitc/netsuite-types declares for N/record. Models import it from this package
 * instead of from N/record, because the build step evaluates model files outside NetSuite and only
 * lets them import this package. Run after bumping @hitc/netsuite-types: `npm run generate:record-types`.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const require = createRequire(import.meta.url);
const repositoryRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const outputFile = path.join(repositoryRoot, 'src', 'model', 'netsuite-record-type.ts');

export function readNetsuiteRecordTypeEntries() {
    const declarationFile = require.resolve('@hitc/netsuite-types/N/record.d.ts');
    const typesVersion = require('@hitc/netsuite-types/package.json').version;
    const source = readFileSync(declarationFile, 'utf8');
    const enumBlock = source.match(/export enum Type \{([^}]*)\}/);
    if (!enumBlock) throw new Error(`No 'export enum Type' found in ${declarationFile}.`);
    const entries = [...enumBlock[1].matchAll(/^\s*([A-Z][A-Z0-9_]*)\s*=\s*'([a-z0-9_]+)'/gm)].map((match) => [match[1], match[2]]);
    if (entries.length === 0) throw new Error(`'export enum Type' in ${declarationFile} has no string members.`);
    return { entries, typesVersion };
}

export function renderNetsuiteRecordTypeSource({ entries, typesVersion }) {
    const members = entries.map(([key, value]) => `    ${key} = '${value}',`).join('\n');
    return `// Generated by scripts/generateNetsuiteRecordTypes.mjs from @hitc/netsuite-types ${typesVersion} (N/record Type). Do not edit.

/**
 * The native NetSuite record types, as N/record names them: \`@RecordType(NetsuiteRecordType.SALES_ORDER)\`.
 * A runtime copy of N/record's \`Type\` enum, so a model file needs no N/* import; a custom record is
 * still named by its id, \`@RecordType('customrecord_x')\`.
 */
export enum NetsuiteRecordType {
${members}
}
`;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
    const rendered = renderNetsuiteRecordTypeSource(readNetsuiteRecordTypeEntries());
    writeFileSync(outputFile, rendered);
    console.log(`Wrote ${path.relative(repositoryRoot, outputFile)}.`);
}
